# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmTvu45j0w76kdik1gjvO6SB7sAm7KtP
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score
)

from sklearn.utils import resample

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("cleaned_data.csv")

print(df.head())

print(df.shape)

y_reg = df["MSRP"]
y_clf = (df["MSRP"] > df["MSRP"].median()).astype(int)

print(y_clf.value_counts())

X = df.drop(columns=["MSRP"])

cat_cols = X.select_dtypes(include=["object","category"]).columns

cat_cols

X = pd.get_dummies(
    X,
    columns=cat_cols,
    drop_first=True
)

print(X.shape)

X_train, X_test, y_train_reg, y_test_reg = train_test_split(
    X,
    y_reg,
    test_size=0.20,
    random_state=42
)

_, _, y_train_clf, y_test_clf = train_test_split(
    X,
    y_clf,
    test_size=0.20,
    random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

linear = LinearRegression()

linear.fit(
    X_train_scaled,
    y_train_reg
)

y_pred = linear.predict(X_test_scaled)

mse = mean_squared_error(
    y_test_reg,
    y_pred
)

r2 = r2_score(
    y_test_reg,
    y_pred
)

print("MSE :", mse)

print("R2 :", r2)

coef = pd.DataFrame({

    "Feature":X.columns,

    "Coefficient":linear.coef_

})

coef["Absolute"] = coef["Coefficient"].abs()

coef = coef.sort_values(
    "Absolute",
    ascending=False
)

coef.head(10)

coef.head(3)

# Train Ridge Regression Model

ridge = Ridge(alpha=1.0)

ridge.fit(X_train_scaled, y_train_reg)

# Prediction
ridge_pred = ridge.predict(X_test_scaled)

# Evaluation
ridge_mse = mean_squared_error(y_test_reg, ridge_pred)
ridge_r2 = r2_score(y_test_reg, ridge_pred)

print("Ridge MSE :", ridge_mse)
print("Ridge R² :", ridge_r2)

comparison = pd.DataFrame({

    "Model":["Linear Regression","Ridge Regression"],

    "MSE":[mse,ridge_mse],

    "R²":[r2,ridge_r2]

})

comparison

print("Training Class Distribution")

print(y_train_clf.value_counts())

class_ratio = y_train_clf.value_counts(normalize=True)

print(class_ratio)

logistic = LogisticRegression(

    max_iter=1000,

    class_weight="balanced",

    random_state=42

)

logistic.fit(

    X_train_scaled,

    y_train_clf

)

y_pred = logistic.predict(X_test_scaled)

y_probability = logistic.predict_proba(X_test_scaled)[:,1]

cm = confusion_matrix(

    y_test_clf,

    y_pred

)

cm

plt.figure(figsize=(6,5))

sns.heatmap(

    cm,

    annot=True,

    cmap="Blues",

    fmt="d"

)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

print(

classification_report(

    y_test_clf,

    y_pred

)

)

accuracy = logistic.score(

    X_test_scaled,

    y_test_clf

)

precision = precision_score(

    y_test_clf,

    y_pred

)

recall = recall_score(

    y_test_clf,

    y_pred

)

f1 = f1_score(

    y_test_clf,

    y_pred

)

print("Accuracy :",accuracy)

print("Precision :",precision)

print("Recall :",recall)

print("F1 Score :",f1)

fpr,tpr,threshold = roc_curve(

    y_test_clf,

    y_probability

)

auc = roc_auc_score(

    y_test_clf,

    y_probability

)

plt.figure(figsize=(8,6))

plt.plot(

    fpr,

    tpr,

    label=f"AUC = {auc:.3f}"

)

plt.plot([0,1],[0,1],'r--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve")

plt.legend()

plt.show()

"""Markdown
ROC Interpretation

An ROC curve closer to the upper-left corner indicates better classification performance.

The AUC measures the probability that the classifier ranks a randomly chosen positive sample higher than a randomly chosen negative sample.

AUC = 1.0 → Perfect classifier
AUC = 0.5 → Random guessing
"""

thresholds = np.arange(0.30,0.71,0.10)

results=[]

for t in thresholds:

    pred=(y_probability>=t).astype(int)

    results.append([

        t,

        precision_score(y_test_clf,pred),

        recall_score(y_test_clf,pred),

        f1_score(y_test_clf,pred)

    ])

threshold_table=pd.DataFrame(

    results,

    columns=[

        "Threshold",

        "Precision",

        "Recall",

        "F1 Score"

    ]

)

threshold_table

best = threshold_table.loc[

    threshold_table["F1 Score"].idxmax()

]

best

"""Markdown
Precision Formula
Precision=
(TP+FP)/
TP
	​

Recall Formula
Recall=
(TP+FN)/
TP
	​


Higher thresholds increase Precision but decrease Recall.

Lower thresholds increase Recall but may introduce more False Positives.

The threshold with the highest F1-score provides the best balance between Precision and Recall.
"""

regularized = LogisticRegression(

    C=0.01,

    max_iter=1000,

    random_state=42

)

regularized.fit(

    X_train_scaled,

    y_train_clf

)

reg_probability = regularized.predict_proba(

    X_test_scaled

)[:,1]

reg_prediction = regularized.predict(

    X_test_scaled

)

comparison=pd.DataFrame({

"Model":["C = 1.0","C = 0.01"],

"Precision":[

precision_score(y_test_clf,y_pred),

precision_score(y_test_clf,reg_prediction)

],

"Recall":[

recall_score(y_test_clf,y_pred),

recall_score(y_test_clf,reg_prediction)

],

"AUC":[

roc_auc_score(y_test_clf,y_probability),

roc_auc_score(y_test_clf,reg_probability)

]

})

comparison

"""Markdown
What does C control?

The parameter C is the inverse of regularization strength.

Larger C → weaker regularization.
Smaller C → stronger regularization.

Reducing C shrinks coefficients more aggressively, helping prevent overfitting but potentially reducing predictive performance.
"""

auc_difference=[]

for i in range(500):

    index=np.random.choice(

        len(y_test_clf),

        len(y_test_clf),

        replace=True

    )

    auc1=roc_auc_score(

        y_test_clf.iloc[index],

        y_probability[index]

    )

    auc2=roc_auc_score(

        y_test_clf.iloc[index],

        reg_probability[index]

    )

    auc_difference.append(

        auc1-auc2

    )

mean_difference=np.mean(auc_difference)

lower=np.percentile(

    auc_difference,

    2.5

)

upper=np.percentile(

    auc_difference,

    97.5

)

print("Mean Difference :",mean_difference)

print("95% Confidence Interval")

print(lower)

print(upper)